### ISSUE TITLE
Basic units of measurement for Time

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#10]
Thanks @teunw for adding the basic time units via #35!

`namespace UnitConverter\Unit\Time;`

* [x] Millisecond = `ms`
* [x] Second = `s` 
* [x] Hour = `hr` 
* [x] Minute = `min`
* [x] Day = `day`
* [x] Month (31 days) = `month` 
* [x] Microsecond = `μs`
* [x] Nanosecond = `ns`
* [x] Week = `week`
* [x] Year (365 days) = `year`

**Comment by teunw** [comment]
I think it might be better to make the month and year units calculatable.
So giving the years to convert from/to would give different results based on leap years for instance.

**Comment by jordanbrauer** [comment]
@teunw Great idea! How do you imagine the implementation of calculable months/years working?

I think we could make this work by implementing the `::calculate()` class method on the Month and Year units (see Celsius & Fahrenheit units).
