### ISSUE TITLE
Basic units of measurement for Energy (Power)

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#11]
`namespace UnitConverter\Unit\Energy;`

* [x] Joule = `j`
* [x] Calorie = `cal`
* [x] Foot Pound = `ftlb`
* [x] Kilojoule = `kj` (thanks @andrewboerema)
* [x] Kilowatt Hour = `kwhr` (thanks @andrewboerema)
* [x] Mega Electron Volt = `mev` (thanks @andrewboerema)
* [x] Megajoule = `mj` (thanks @andrewboerema)
* [x] Megawatt Hour = `mwhr` (thanks @andrewboerema)
* [x] Newton Meter = `Nm` (thanks @andrewboerema)
* [x] Watt Hour = `whr`

**Comment by jordanbrauer** [comment]
jiggawatt ? 😎

**Comment by andrewboerema** [comment]
@jordanbrauer - Check out #33
