### ISSUE TITLE
[7.0.1][FatalErrorException] BinaryCalculator::round must be compatible with UnitConverter\Calculator\AbstractCalculator::round

### ISSUE THREAD

**Issue by StenKoning** [jordanbrauer/unit-converter#115]
Currently I can't run my code because the BinaryCalculator's round method doesn't match the AbstractCalculator's round method signature (abstract requires float, while binary returns string).

Console error message:
_Declaration of UnitConverter\Calculator\BinaryCalculator::round($value, ?int $precision = NULL): string must be compatible with UnitConverter\Calculator\AbstractCalculator::round($value, ?int $precision = NULL): float_

**Comment by StenKoning** [comment]
$calculator = new BinaryCalculator();

    $amountOfEggs = $faker->numberBetween(400, 60000);
```
    $converter = UnitConverter::createBuilder()
        ->addBinaryCalculator()
        ->addDefaultRegistry()
        ->build();

    $totalWeight =
        $converter
            ->convert($calculator->mul('70', $amountOfEggs))
            ->from('g')->to('kg');
```

**Comment by jordanbrauer** [comment]
Hey, that is for the report! I'll take a look today.

**Comment by jordanbrauer** [comment]
In the meantime @StenKoning, a couple of questions for you – 

1. What version of PHP are you using? I believe there were return type issues in the early versions of `7.0.*`.
2. Is `$amountOfEggs` a string? If not, this will also cause an error. You can fix that by casting it to a string.
    ```php
    $amountOfEggs = (string) $faker->numberBetween(400, 60000);
    ```

**Comment by StenKoning** [comment]
Hi Jordan,

I'm using php version: PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS ).

I casted the value of $amountOfEggs to string like you said. See the attached screenshot for the error.

![image](https://user-images.githubusercontent.com/3466148/43734280-81258d86-99b7-11e8-9824-5a9b0d12012f.png)

**Comment by StenKoning** [comment]
![image](https://user-images.githubusercontent.com/3466148/43734345-b427b47a-99b7-11e8-8220-644531ea4fee.png)

**Comment by jordanbrauer** [comment]
Hm, this is quite strange, as I cannot reproduce the error. I've adjusted the method signatures to resolve the error, though. 

Can you update your composer require for this package to `master`, and see if the error is resolved for you now? If the error is resolved, let me know so that I can tag and release a new version under `0.8.0`. 🙂

**Comment by StenKoning** [comment]
Hi,

Issue has been resolved in "master".

**Comment by jordanbrauer** [comment]
Wonderful! 🎉 Version `0.8.0` is now live. Make sure that you update your `composer.json` file to the new version so that you don't receive unstable changes in `master`.
