### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#120]
Happened while executing the benchmark script at `bin/benchmark`.

```
Warning: Division by zero in src/UnitConverter/Calculator/SimpleCalculator.php on line 46
```

**Comment by jordanbrauer** [comment]
Another occurrence while passing non-numeric values through binary calculator

```php
UnitConverter::binary()
    ->convert('39as')
    ->from('g')
    ->to('mg');
``` 

produces

```
Warning: bcdiv(): Division by zero in src/Calculator/BinaryCalculator.php on line 60
```

**Comment by kylewallace** [comment]
Hey mate, not sure if you are still working on this project but I have been stuffing around with it and came across the same bug. I have very limited knowledge of PHP (and math for that matter) so I don't even know if this is relevant info. I was able to reproduce the bug by attempting to convert a volume unit and returning all possible conversions.

`return UnitConverter::createBuilder()->addSimpleCalculator()->addDefaultRegistry()->build()->convert(1)->from('mL')->all();`

My log file indicates that the calculator tried to perform a conversion to km/l before throwing an error:

```
#4 MYDIRECTORY\\vendor\\jordanbrauer\\unit-converter\\src\\UnitConverter.php(314): UnitConverter\\UnitConverter->calculate()
#5 MYDIRECTORY\\vendor\\jordanbrauer\\unit-converter\\src\\UnitConverter.php(171): UnitConverter\\UnitConverter->to('km/l')
#6 [internal function]: UnitConverter\\UnitConverter->UnitConverter\\{closure}('km/l')
#7 MYDIRECTORY\\vendor\\jordanbrauer\\unit-converter\\src\\UnitConverter.php(173): array_map(Object(Closure), Array)
```

 To my knowledge km/l is a **fuel economy** unit so I had a look at that unit and it has been defined as a unit of **volume**.

Could this be causing the issue or does it at least point you in the right direction?

**Comment by jordanbrauer** [comment]
Hey @kylewallace ! Thanks a bunch for taking the time to share your info to reproduce the error, and for choosing this package as your unit conversion tool. Project is still maintained, yes, though I've unfortunately had less time in the past year.

I'll take a peek at this later and see what's going on, using the snippet you've provided as a jumping off point.

**Comment by jordanbrauer** [comment]
Hey @kylewallace ! I just merged a fix for this into `master`. I used the following snippet (the same you provided me) to reproduce and things should be in working order now! It turned out to be exactly as you said

> To my knowledge km/l is a fuel economy unit so I had a look at that unit and it has been defined as a unit of volume.

```php
UnitConverter::createBuilder()
    ->addSimpleCalculator()
    ->addDefaultRegistry()
    ->build()
    ->convert(1, 6)
    ->from('mL')
    ->all()
```

You can update to the latest version `0.8.5` and receive the fix there!
