### ISSUE TITLE
Add `.gitattributes` to project to prevent exporting test sources, artifacts, as well as PHARs committed to the repository

### ISSUE THREAD

**Issue by Ocramius** [jordanbrauer/unit-converter#153]
### Summary

Noticed this because `bin/phpdoc.phar` is committed to the repo, but in general applies to all sources that aren't vital (or legally necessary, such as `LICENSE`) downstream: they should not be part of the release distribution.

### Steps to reproduce

```sh
composer require jordanbrauer/unit-converter --prefer-dist
ls vendor/jordanbrauer/unit-converter # lists `/bin`
```

### What is the expected *correct* behavior?

`bin`, as well as `tests`, `.vscode`, `.github`, `.circleci`, etc. should not be in the `vendor` path when installing a distribution release.

### Possible fixes 

See for example https://github.com/Ocramius/ProxyManager/blob/2.8.0/.gitattributes: adding such a file to a new minor release would solve the immediate pain :+1:

**Comment by jordanbrauer** [comment]
Awesome! Thanks for the heads up @Ocramius – I will get on that later today after work, unless you happen to send an MR in before that. 🙂

**Comment by Ocramius** [comment]
Would've sent patch, but did report this from my phone :-)

Under release crunch myself too, heh...

**Comment by jordanbrauer** [comment]
This has been taken care of. New output after applying the patch (or upgrading from `0.8.3` to `0.8.4`) shows that there are no more useless artifacts in the distributed package!

```shell
tree -L 1 vendor/jordanbrauer/unit-converter
```

will output

```
vendor/jordanbrauer/unit-converter
├── CHANGELOG.md
├── LICENSE
├── README.md
├── SECURITY.md
├── composer.json
└── src

1 directory, 5 files
```

**Comment by Ocramius** [comment]
thank you!
