### ISSUE TITLE
CoversionFormula throws a TypeError

### ISSUE THREAD

**Issue by smarttoolsbox** [jordanbrauer/unit-converter#177]
### Summary

Instead of php TypeError formula should throw a convertor exception

### Steps to reproduce

```
(new ConverterBuilder())->addBinaryCalculator()->addDefaultRegistry()->build()
                    ->convert(1)
                    ->from('kg')
                    ->to('F');
```

### What is the current *bug* behavior?

throws a TypeError with message `Argument 2 passed to UnitConverter\Calculator\BinaryCalculator::mul must be of the type string, string given`

(What you should see instead)

A Converter exception

**Comment by smarttoolsbox** [comment]
maybe it should allow conversion of same `unitOf` only

**Comment by smarttoolsbox** [comment]
UnitConverter line 358
```
$this->guardAgainstBadConversion();
```
```
private function guardAgainstBadConversion()
{
    if($this->from->getUnitOf() !== $this->to->getUnitOf()) {
        throw new BadConversion(...);
    }
}
```

**Comment by jordanbrauer** [comment]
Checking later today – thanks @smarttoolsbox! My apologies for the delay in response :)
