### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by ashleyhood** [jordanbrauer/unit-converter#184]
What are the plans to enable PHP 8.2 for this package? I know that PHP 8.2 has only just been released so not expecting immediate support but just to help with future planning.

**Comment by jordanbrauer** [comment]
See #185 and #186 for details (:

**Comment by jordanbrauer** [comment]
Closing, as this has been resolved by #186 and a new release has been made at `v0.9.0`. ＼(＾▽＾)／
