### ISSUE TITLE
Add support for units of measurement, Digital Storage

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#40]
## Digital Storage

`namespace UnitConverter\Unit\DigitalStorage`

* [ ] The abstract `DigitalStorageUnit` class exists for all subsequent data transfer rate units to extend from.
  * [ ] It declares the protected property `$baseUnit` as `Bit::class`.
  * [ ] It declares the protected property `$unitOf` as `Measure::DIGITAL_STORAGE`.

### Bit Storage Units (Decimal)

* [ ] **bit (`b`) = `1`**
* [ ] kilobit (`kb`) = `1000`
* [ ] megabit (`Mb`) = `1000000`
* [ ] gigabit (`Gb`) = `1000000000`
* [ ] terabit (`Tb`) = `1000000000000`

### Bit Storage Units (Binary)

* [ ] kibibit (`Kib`) = `1024`
* [ ] mebibit (`Mib`) = `1049000`
* [ ] gibibit (`Gib`) = `1074000000`
* [ ] tebibit (`Tib`) = `1100000000000`

### Byte Storage Units (Decimal)

* [ ] byte (`B`) = `8`
* [ ] kilobyte (`kB`) = `8000`
* [ ] megabyte (`MB`) = `8000000`
* [ ] gigabyte (`GB`) = `8000000000`
* [ ] terabyte (`TB`) = `8000000000000`

**Comment by laurent35240** [comment]
Hi,

I created this PR #148 for supporting Digital storage units

Laurent

**Comment by jordanbrauer** [comment]
Thanks a lot @laurent35240! Merged it in – happy halloween 🎃
