### ISSUE TITLE
Add support for units of measurement, Fuel Economy

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#42]
## Fuel Economy

`namespace UnitConverter\Unit\FuelEconomy;`

### Units of Fuel Economy

* [x] **kilometre per litre (`km/l`) = `1`**
* [x] miles per gallon (US) (`mpg`) = `2.35215`
* [x] miles per gallon (UK) (`mpg`) = `2.82481`
* [x] litre per 100 kilometres (`L/100km`) = `100`

**Comment by Progi1984** [comment]
I'm on it :)

**Comment by Progi1984** [comment]
@jordanbrauer It's done : PR #117

**Comment by jordanbrauer** [comment]
Awesome! Thanks, @Progi1984. I'll give it a look & merge it in after work.
