### ISSUE TITLE
Add new unit property, "scientificSymbol" for special unicode character symbols

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#46]
Could be useful for when needing to output symbols as scientific notation rather than "shorthand notation", especially because typing special unicode characters is not fun.

See #45 for more details (**very** related + answers to "problem" in PDFs).

### Specs

* [x] The property should be added to the `UnitConverter\Unit\AbstractUnit` abstract class.
* [x] The property should be of type `string`.
* [x] The property should have matching setter method;
```php
public function setScientificSymbol (string $scientificSymbol) : UnitInterface;
```
* [x] The property should have matching getter method;
```php
public function getScientificSymbol () : string;
```

**Comment by luchianenco** [comment]
added, please take a look:
https://github.com/jordanbrauer/unit-converter/pull/47

**Comment by jordanbrauer** [comment]
Thanks a bunch @luchianenco! 😃
