### ISSUE TITLE
Implement indication of metric(si)/imperial systems

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#87]
Could probably be done at the class level, e.g.,

```php
use LengthUnit;

abstract class MetricLengthUnit extends LengthUnit;

abstract class ImperialLengthUnit extends LengthUnit;
```

Not sure though - just an idea.

**Comment by Gummibeer** [comment]
Wouldn't a general trait be better instead of extending every class with two more classes?

**Comment by jordanbrauer** [comment]
@Gummibeer interesting idea. I am not really a fan of traits, as they get very messy and close to magic. I am not even sure that interfaces are the correct place for this anymore, either (see ticket is almost 2 years ago).

Care to extrapolate on your thoughts a little more?

**Comment by Gummibeer** [comment]
After checking some units a bit more I found some more problems. Let's take angle units as an example.
"Common" are Turns, Radians, Degrees and Gradians.
Metric would be `Gradians`, SI is `radian` and imperial has no angle unit but nearly everywhere used is `Degrees` and in normal life sometimes turns, even if no one knows that it's an unit.

So I would introduce some interfaces, that doesn't define any method but allow instance of checks.
`Angle::make(90, 'degree') instanceof SIUnit/MetricUnit/ImperialUnit`.

**Comment by jordanbrauer** [comment]
Very nice @Gummibeer – thanks for looking at this!

> After checking some units a bit more I found some more problems. Let's take angle units as an example.
> "Common" are Turns, Radians, Degrees and Gradians.

Sounds like you're saying we need to add unit implementations for `Turn` and `Gradian` then? I am okay with that!

> Metric would be `Gradians`, SI is `radian` and imperial has no angle unit but nearly everywhere used is `Degrees` and in normal life sometimes turns, even if no one knows that it's an unit.

Correct me if I am wrong, but all SI units are metric but not all metric units are necessarily SI. From [the degree unit's Wikipedia page](https://en.wikipedia.org/wiki/Degree_(angle)), I read this:

> _It is not an SI unit, as the SI unit of angular measure is the radian, but **it is mentioned in the SI brochure as an accepted unit**. Because a full rotation equals 2π radians, one degree is equivalent to π÷180 radians._

From my perspective and understanding, it is possible for a unit to have one, many, or none for it's families. Any ideas for how we classify units that are part of neither metric, SI, or imperial families? Should we even classify them?

Apologies for the late reply – got busy with work!

**Comment by Gummibeer** [comment]
No Problem! 😉
Yes, because of the possible multiple families/systems I think that interfaces would be great!?
So far I've understood angle is an example for different SI and metric units. Radian isn't metric (not a multiple of 10). Gradians are - 100 per 1/4turn or 400 per full turn.

**Comment by jordanbrauer** [comment]
work started in #151
