### ISSUE TITLE
Basic units of measurement for Pressure

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#9]
`namespace UnitConverter\Unit\Pressure;`

* [x] Pascal = `pa`
* [x] Pounds per Square Inch = `psi`
* [x] Bar = `bar`
* [x] Kilopascal = `kpa` (thanks @arubacao)
* [x] Megapascal = `mpa` (thanks @arubacao)
* [x] Millibar = `mbar` (thanks @teunw)
* [x] Atmosphere = `atm`

**Comment by teunw** [comment]
I submitted a pull request, see what you think. I'm open for suggestions.
